-- MODELAGEM COMERCIO_OLTP

CREATE DATABASE COMERCIO_OLTP_1
		GO

		USE COMERCIO_OLTP
		GO

		CREATE TABLE CLIENTE(
			IDCLIENTE INT PRIMARY KEY IDENTITY,
			NOME VARCHAR(15) NOT NULL,
			SOBRENOME VARCHAR(30) NOT NULL,
			EMAIL VARCHAR(60) NOT NULL,
			SEXO CHAR(1) NOT NULL,
			NASCIMENTO DATE NOT NULL,
			ID_ENDERECO INT NOT NULL
		)	
		GO

		CREATE TABLE ENDERECO(
			IDENDERECO INT PRIMARY KEY IDENTITY,
			RUA VARCHAR(100) NOT NULL,
			CIDADE VARCHAR(50) NOT NULL,
			ESTADO VARCHAR(20) NOT NULL,
			REGIAO VARCHAR(20) NOT NULL,
			
		)
		GO

		CREATE TABLE VENDEDOR(
			IDVENDEDOR INT PRIMARY KEY IDENTITY,
			NOME VARCHAR(35) NOT NULL,
			SEXO CHAR(1) NOT NULL,
			EMAIL VARCHAR(60) NOT NULL,
			ID_GERENTE INT
		)
		GO

		CREATE TABLE CATEGORIA(
			IDCATEGORIA INT PRIMARY KEY IDENTITY,
			NOME VARCHAR(30) NOT NULL
		)
		GO

		CREATE TABLE FORNECEDOR(
			IDFORNECEDOR INT PRIMARY KEY IDENTITY,
			NOME VARCHAR(50) NOT NULL
		)
		GO

		CREATE TABLE PRODUTO(
			IDPRODUTO INT PRIMARY KEY IDENTITY,
			PRODUTO VARCHAR(100) NOT NULL,
			VALOR NUMERIC(10,2) NOT NULL,
			CUSTO_MEDIO NUMERIC(10,2)NOT NULL,
			ID_CATEGORIA INT,
			ID_FORNECEDOR INT
		)
		GO

		CREATE TABLE FORMA_PAGAMENTO(
			IDFORMA INT PRIMARY KEY IDENTITY,
			FORMA VARCHAR(40) NOT NULL
		)
		GO

		CREATE TABLE ITEM_NOTA(
			IDITEMNOTA INT PRIMARY KEY IDENTITY,
			ID_PRODUTO INT ,
			ID_NOTA_FISCAL INT,
			QUANTIDADE INT,
			TOTAL NUMERIC(10,2)	
		)
		GO

		CREATE TABLE NOTA_FISCAL(
			IDNOTA INT PRIMARY KEY IDENTITY(10,10),
			DATA DATE,
			TOTAL NUMERIC(10,2),
			ID_FORMA INT,
			ID_CLIENTE INT,
			ID_VENDEDOR INT
		)
		GO


		ALTER TABLE VENDEDOR ADD CONSTRAINT FK_GERENTE
FOREIGN KEY(ID_GERENTE) REFERENCES VENDEDOR(IDVENDEDOR)
GO

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_VENDEDOR
FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR)
GO

ALTER TABLE ITEM_NOTA ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
GO

ALTER TABLE ITEM_NOTA ADD CONSTRAINT FK_ITEM_NOTAFISCAL
FOREIGN KEY(ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL(IDNOTA)
GO

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_FORNECEDOR
FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
GO


ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
GO

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO)
GO

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_FORMA
FOREIGN KEY(ID_FORMA) REFERENCES FORMA_PAGAMENTO(IDFORMA)
GO